### ISSUE TITLE
60 min timer resets when a new chunk loads.

### ISSUE THREAD

**Issue by gnorfix** [zmanowar/random-event-analytics#10]
Hello, I've been running around a lot and noticed, that every time a new chunk loads that I run by the timer just resets back to 60min.

It also reset when I entered a quest cutscene.

**Comment by zmanowar** [comment]
Good call, checking it out shortly. I think I know the cause.

**Comment by zmanowar** [comment]
To clarify as well, it looks like the 5 minute timer was being reset. Should be fixed in https://github.com/zmanowar/random-event-analytics/commit/f73db5c913bb2eb2fa3b744dffb795e08dfee9ad
