### ISSUE TITLE
UI disappeared?

### ISSUE THREAD

**Issue by Pikkufighter** [zmanowar/random-event-analytics#14]
Hello!

I have an issue with the random event analytics not existing on my game window. sending a screenshot that shows that its active but nowhere to be found. Did also try to make the runelite window as large as possible (3 screens wide) still nothing. Reinstall did not help either.

![image](https://user-images.githubusercontent.com/47358705/236674892-caa0e34d-d5fb-435f-815b-8f89685f121f.png)

**Comment by zmanowar** [comment]
Hello! Sorry for the issues.

Would you mind uploading your client log?

- Navigate to %userprofile%.runelite\logs on Windows or $HOME/.runelite/logs on Linux and macOS
- Upload the log file named client.log

If you're feeling super resourceful starting Runelite in debug mode, logging in to reproduce the issue, then uploading the logs is even better!

> Launch RuneLite in debug mode using the following command:

`"%localappdata%\runelite\runelite.exe" --debug`

(or by launching the Runelite (Configure) app

Few other questions:
- Are you using a Jagex account (or the rune launcher)?
- Do your randoms still appear in the side bar?

This could be related to https://github.com/zmanowar/random-event-analytics/issues/11 -- although I'm not able to reproduce either at the moment, need more information.

**Comment by Pikkufighter** [comment]
[client_2023-05-07.0.log](https://github.com/zmanowar/random-event-analytics/files/11423652/client_2023-05-07.0.log)
I'm not using a Jagex account and it does appear in the sidebar.

**Comment by zmanowar** [comment]
Thanks for the upload, I'll take a deeper look when I get home but it looks like there were issues with `ConfigManager`. https://github.com/runelite/plugin-hub/pull/4309 was merged about 3 hours ago that was supposed to fix / help that issue. Could you try restarting your client and seeing if it's fixed?

**Comment by Pikkufighter** [comment]
Yes it is now showing up for me after installing it again, thank you!
