### ISSUE TITLE
Random events not being logged or causing 'Eligible In' timer to reset

### ISSUE THREAD

**Issue by Invalids** [zmanowar/random-event-analytics#16]
Random events don't seem to be going into the log or resetting the 'Eligible In Overestimate' timer, it seems to have started with yesterday's Runelite update.  I still got a notification for the spawn ( Which I think was from this plugin) but no logging. Others in my CC had the issue as well.

**Comment by zmanowar** [comment]
Looking into this, the randoms I've received have been logged and the timer resets.

Was it a particular random or all? RL updated the way the Frog event is handled, I wonder what else has changed -- I'll take a look. Do you happen to have the "Hide Random Events" config turned on in the Entity Hider plugin?

FWIW the only notifications this plugin currently supports is for the Strange Plant, the other randoms are handled by the RL "Random Events" plugin.

**Comment by zmanowar** [comment]
Just had it happen with a sandwich lady.

**Comment by Invalids** [comment]
It’s at least randoms that I’ve seen today. I’ve had Giles, Jekyll, Mysterious old Man, and Drunken Dwarf today and and none were logged or reset the timer. I don’t have randoms set to hidden in the entity hider, but I do use the random event hider plugin, set to hide everyone else’s random events while showing all of my own, with the options to mute and hide the poof

**Comment by zmanowar** [comment]
I found the issue, fixing shortly.

**Comment by zmanowar** [comment]
PR was merged, should be updated on the plugin hub shortly. You'll need to relaunch the game to receive the update. My apologies to you and your clan mates, good luck out there -- let me know if you find anything else.

**Comment by zmanowar** [comment]
Had a random spawn and it logged + reset the timer. Closing for now!
