### ISSUE TITLE
Intervals On Bar Not Updating

### ISSUE THREAD

**Issue by zmanowar** [zmanowar/random-event-analytics#6]
From https://github.com/zmanowar/random-event-analytics/issues/3:

> It was successfully logged, but it was my first random to spawn since the conversion so that seems like a likely explanation.  Though it seems like the overlay debug tick counter did update, just not the countdown/intervals.  I took this picture at 11:00, which is 47 minutes since the previous random.  If you convert the ticks to minutes, you get a little less than 46 minutes (I spent a small amount of time logged out/hopping worlds testing things), so that seemed to update just fine.

![image](https://user-images.githubusercontent.com/94253934/236103979-0b6dc3f2-e6b1-4d99-9be1-ce9e2c13aea8.png)

>I'll update my comment to say what happens when the next one spawns.

_Originally posted by @samszotkowski in https://github.com/zmanowar/random-event-analytics/issues/3#issuecomment-1534007755_

**Comment by zmanowar** [comment]
Creating a new issue here to track this -- the bar most likely reset but the total "Intervals" counter did not. I think I see the issue. Intervals is based on current logged-in time -- may need a secondary counter for last spawn. 

Technically the panel calls [getIntervalsSinceLastRandom](https://github.com/zmanowar/random-event-analytics/blob/master/src/main/java/com/randomEventAnalytics/TimeTracking.java#L125), which calculates the number of intervals as a basis of logged in time.

I _think_ modifying `getCurrentSessionNumIntervals` to reference the last spawned time in conjunction with the login time might be the fix. Will probably end up writing a test to check a few things.

**Comment by samszotkowski** [comment]
![image](https://user-images.githubusercontent.com/94253934/236110660-d078406c-90de-4b7a-bc38-aa78bad4ead4.png)
Most things seem to be working properly after my next random spawned, but the interval counter gets updated to show how many intervals since login, and delta event time recorded in the log shows the time since login instead of the time since last random.

**Comment by zmanowar** [comment]
Most likely solved in https://github.com/zmanowar/random-event-analytics/commit/39c6d6e54d3f8e67538f80156eabafebe7577ae7. The entire tracking for `secondsSinceLastRandomEvent` was janky. 

Intervals may still be broken, going to investigate a bit further.
